version: '3.5'

services:
  train:
    container_name: treebeard_vit
    build:
      context: ./
      dockerfile: Dockerfile
    shm_size: 8G
    volumes:
      - "/mnt/data-nas/:/mnt/data-nas"
      - "/data/:/data/"
      - ".:/home/workspace/treebeard_vit"
    expose:
      - "17000"
    ports:
      - "17000:22"
    environment:
      - RUN_TYPE=train # train: train.py 실행, test: test.py 실행
      - CONFIG_PATH=/home/workspace/treebeard_vit/config/vit16small224/config.json # train 또는 test 관련 configuration file
    ipc: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # can use and watch all gpus
              capabilities: [ gpu ]